name: Firebase Backup

on:
  schedule:
    - cron: '0 9 * * *' # every day at 12 noon EAT (which is UTC+3)

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: my-love-18013
          service_account_key: ${{ secrets.GCP_SA_KEY_OPENSIGNAL }}
          export_default_credentials: true

      - name: Backup Firestore
        run: |
          gcloud firestore export gs://my-love-18013.appspot.com/firestore-backups/$(date +%F)
